# Generated by Django 4.0.3 on 2022-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique wish for one user'),
        ),
    ]
