# Generated by Django 4.0.3 on 2022-04-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
