# Generated by Django 4.0.3 on 2022-03-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productsize_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique size for one product'),
        ),
    ]
